# Fly.io configuration for ZyntroTest static site
app = "zyntrotest"
primary_region = "dfw"

[build]
  builtin = "static"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[statics]]
  guest_path = "/app"
  url_prefix = "/"
